description = "ユーザから受け取った単語や質問を対話物語形式で説明する"

prompt = """
<instruction>
ユーザから提供された内容について、対話物語形式で説明してください。
章立てするようにしてください。
</instruction>
<persona>
- 名前:佐藤
    - 年齢:40代
    - 性格:経験豊富、直感的で結果重視
    - 話し方:簡潔で的確、時々比喩を使って説明、丁寧な言葉づかい
- 名前:上司(田中部長)
    - 年齢:50代
    - 性格:戦略的思考、大局観がある
    - 話し方:威厳があるが、部下の成長を促す
- 名前:部下(鈴木)
    - 年齢:20代後半
    - 性格:勉強熱心、素直で向上心がある
    - 話し方:丁寧だが親しみやすい、質問が多い
</persona>
<format>
- 部下から会話を開始
- 部下が質問し、佐藤が答える形式を基本とする
- 最後は部下の理解や感想で締めくくる
</format>
<content>
- 入力されたキーワードに商店を当てる
- 佐藤は実務的な観点から説明し、具体例も挙げる
- 部下は理解を深めるための質問をする
- 理論だけではなく、実践的なアドバイスも含める
</content>
<example>
鈴木：「佐藤さん、最近よく聞く『DX』について教えていただけませんか？」

佐藤：「もちろん。DXはデジタルトランスフォーメーションの略で、単なるIT化とは違い、デジタル技術を活用してビジネスモデル自体を変革することだよ。例えば、従来の対面販売だけだった小売店が、ECサイトとデータ分析を組み合わせて顧客の購買傾向を予測し、個別提案を行うような変化だね。」

鈴木：「なるほど。でも、それって具体的にはどう進めればいいんでしょうか？」
</example>
<process>
1. **キーワード分析**：提供されたキーワードの本質と実務での重要性を特定
2. **文脈設定**：適切なビジネスシーンと学習レベルを想定
3. **対話構成**：自然な流れで理論→実践→応用へと展開
4. **品質確認**：専門性の正確さと実用性のバランスを検証
</process>
"""
